# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: app_db
    command: --default-authentication-plugin=mysql_native_password && mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATASOURCE_PASSWORD}
    ports:
      - 3307:3306
      